Models/LogClient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SiteVol.Models
{
    public class LogClient
    {
        public String clientName { get; set; }
        public String username { get; set; }
        public String password { get; set; }
        public string CIN { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public int nb_place { get; set; }


    }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteVol.Models;

namespace SiteVol.Controllers
{
    public class ClientsController : Controller
    {
        private volDBEntities db = new volDBEntities();

        // GET: Clients
        public ActionResult Index()
        {
            return View(db.Client.ToList());
        }

        // GET: Clients/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,nom,prenom,CIN,age,username,password")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Client.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,nom,prenom,CIN,age")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Client client = db.Client.Find(id);
            db.Client.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/LogClientController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteVol.Models;

namespace SiteVol.Controllers
{
    public class LogClientController : Controller
    {
        String CS = "Data Source =. ; database=volDB; Integrated Security = SSPI";
        SqlDataReader dr;
        List<Reservation> res = new List<Reservation>();
        List<VolComp> vol = new List<VolComp>();

        // GET: LogClient

        [HttpGet]
        [Authorize]
        public ActionResult Login()
        {
            return View();
        }

        [HttpGet]
        
        public ActionResult Booking( string id_vol, string destination, string date_depart, string prix, string compagnie)
        {
            
            using (SqlConnection con = new SqlConnection(CS))
            {
                SqlCommand cmd = new SqlCommand("INSERT INTO reservation ([id_vol],[destination],[date_depart],[prix],[compagnie]) VALUES ('" + id_vol + "','" + destination + "','" + date_depart + "','" + prix + "','" + compagnie + "')", con);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();
            }

            return View("Booking");
        }
        [HttpPost]
        public ActionResult Verify(LogClient log)
        {

            using (SqlConnection con = new SqlConnection(CS))
            {
                SqlCommand cmd = new SqlCommand("select * from Client where username = '" + log.username + "' and password = '" + log.password + "' ", con);
                con.Open();
                dr = cmd.ExecuteReader();
                if (dr.Read())
                {
                    log.clientName = log.username;


                    con.Close();
                    return View("ClientMenu", log);
                }
                else
                {
                    con.Close();
                    return View("Error");
                }
            }

        }
        [HttpPost]
        public ActionResult Reserver(Reservation reserv, LogClient logi)
        {
            

            using (SqlConnection con = new SqlConnection(CS))
            {
                SqlCommand cmd = new SqlCommand("UPDATE reservation SET [username]='" + reserv.username + "',[CIN]='"+ reserv.CIN+ "',[nom]='" + reserv.nom + "',[prenom]='" + reserv.prenom + "',[nb_place]='"+ reserv.nb_place + "' WHERE ID = (SELECT max(ID) FROM reservation)", con);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();
                logi.clientName = reserv.username;

                return View("ClientMenu",logi);
              
            }
           
        }
        public void FeachData(string name)
        {
            if (res.Count > 0)
            {
                res.Clear();
            }
            try
            {
                SqlConnection con = new SqlConnection(CS);
                SqlCommand cmd = new SqlCommand("SELECT TOP 1000 [ID],[id_vol],[username],[CIN],[nom],[prenom],[destination],[date_depart],[prix],[nb_place],[compagnie] FROM[volDB].[dbo].[reservation] WHERE username='"+name+"'", con);
                con.Open();
                dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    res.Add(new Reservation()
                    {
                        ID = dr["ID"].ToString(),
                        id_vol = dr["id_vol"].ToString(),
                        username = dr["username"].ToString(),
                        CIN = dr["CIN"].ToString(),
                        nom = dr["nom"].ToString(),
                        prenom = dr["prenom"].ToString(),
                        destination = dr["destination"].ToString(),
                        date_depart = dr["date_depart"].ToString(),
                        prix = dr["prix"].ToString(),
                        nb_place = dr["nb_place"].ToString(),
                        compagnie = dr["compagnie"].ToString()
                    });
                }
                con.Close();

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public ActionResult AnnulerReservation(string name)

        {
            FeachData(name);
            return View(res);
        }
        public ActionResult Delete(int ID, string name, LogClient logi)
        {
            using (SqlConnection con = new SqlConnection(CS))
            {
                SqlCommand cmd = new SqlCommand("DELETE FROM reservation WHERE ID = '"+ID+"'", con);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();
                
                logi.clientName = name;


            }

            return View("ClientMenu",logi);
        }
        public ActionResult Recherche()
        {
            return View();
        }
        public void FeachDataRecherche(VolComp voli)
        {
            if (vol.Count > 0)
            {
                vol.Clear();
            }
            try
            {
                SqlConnection con = new SqlConnection(CS);
                SqlCommand cmd = new SqlCommand("SELECT TOP 1000 [id],[nombre_max],[destination],[ville_depart],[date_depart],[prix],[compagnie] FROM [volDB].[dbo].[Vol] where destination='" + voli.destination + "' and ville_depart='"+voli.ville_depart+"' ", con);
                con.Open();
                dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    vol.Add(new VolComp()
                    {
                        id = dr["id"].ToString(),
                        nombre_max = dr["nombre_max"].ToString(),
                        destination = dr["destination"].ToString(),
                        ville_depart = dr["ville_depart"].ToString(),
                        date_depart = dr["date_depart"].ToString(),
                        prix = dr["prix"].ToString(),
                        compagnie = dr["compagnie"].ToString()
                    });
                }
                con.Close();

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpPost]
        public ActionResult Rechercher(VolComp voli)
        {
            FeachDataRecherche(voli);
            return View("Resultat",vol);
        }
    }
}

Controllers/VolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteVol.Models;

namespace SiteVol.Controllers
{
    public class VolsController : Controller
    {
        private volDBEntities db = new volDBEntities();

        // GET: Vols
        public ActionResult Index()
        {
            return View(db.Vol.ToList());
        }
        public ActionResult Volii()
        {
            return View();
        }

        // GET: Vols/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vol vol = db.Vol.Find(id);
            if (vol == null)
            {
                return HttpNotFound();
            }
            return View(vol);
        }

        // GET: Vols/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vols/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nombre_max,destination,ville_depart,date_depart,prix,compagnie")] Vol vol)
        {
            if (ModelState.IsValid)
            {
                db.Vol.Add(vol);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vol);
        }

        // GET: Vols/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vol vol = db.Vol.Find(id);
            if (vol == null)
            {
                return HttpNotFound();
            }
            return View(vol);
        }

        // POST: Vols/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nombre_max,destination,ville_depart,date_depart,prix,compagnie")] Vol vol)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vol).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vol);
        }

        // GET: Vols/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vol vol = db.Vol.Find(id);
            if (vol == null)
            {
                return HttpNotFound();
            }
            return View(vol);
        }

        // POST: Vols/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Vol vol = db.Vol.Find(id);
            db.Vol.Remove(vol);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/LogClient/AnnulerReservation.cshtml
@model IEnumerable<SiteVol.Models.Reservation>
@{
    ViewBag.Title = "AnnulerReservation";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string[] tabHeads = new string[]{"ID"
      ,"ID de VOL"
      ,"User Name"
      ,"CIN"
      ,"Nom"
      ,"Prenom"
      ,"Destination"
      ,"Date de depart"
      ,"Prix"
      ,"Nombre de places"
      ,"Compagnie" };
    
}
<style>
    th {
        background-color: #0094ff;
        color: white;
    }
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<h2>Annuler Votre Reservation </h2>


<br />

<div class="table">
    <table class="table table table-bordered table-hover">
        <thead>
            <tr>
                @{
                    foreach (var head in tabHeads)
                    {
                        <th>
                            @{
                                @head

                            }
                        </th>

                    }
                }

            </tr>

        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var data in Model)
                    {
                        <tr>
                            <td>@data.ID </td>
                            <td> @data.id_vol </td>
                            <td> @data.username </td>
                            <td> @data.CIN </td>
                            <td> @data.nom </td>
                            <td> @data.prenom </td>
                            <td> @data.destination </td>
                            <td> @data.date_depart </td>
                            <td> @data.prix </td>
                            <td> @data.nb_place </td>
                            <td> @data.compagnie </td>

                            <td>
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "LogClient", new { ID = data.ID, name=data.username })'"> Annuler </button>

                                </div>
                            </td>
                        </tr>

                    }
                }
            }

        </tbody>

    </table>


</div>

Views/LogClient/Booking.cshtml

@{
    ViewBag.Title = "Booking";
    Layout = "~/Views/_Layoutbooking.cshtml";
}


<!---header--->
<div class="header w3ls">
    <h1>Reservation Form</h1>
</div>
<!---header--->
<!---main--->
<div class="main">
    <div class="main-section agile">
        <div class="login-form">
            @using (Html.BeginForm("Reserver", "LogClient", FormMethod.Post))
            {

                    <ul>
                        <li class="text-info">CIN *</li>
                        <li><input type="text" name="CIN" placeholder="" required></li>
                        <div class="clear"></div>
                    </ul>
                    <ul>
                        <li class="text-info">Nom *</li>
                        <li><input type="text" name="nom" placeholder="" required></li>
                        <div class="clear"></div>
                    </ul>
                    <ul>
                        <li class="text-info">Prenom *</li>
                        <li><input type="text" name="prenom" placeholder="" required></li>
                        <div class="clear"></div>
                    </ul>
                    <ul>
                        <li class="text-info">User Name *</li>
                        <li><input type="text" name="username" placeholder="" required></li>
                        <div class="clear"></div>
                    </ul>


                    <ul>
                        <li class="text-info">Nombre de Places *</li>
                        <li class="se">
                            <select class="time-dropdown form-dropdown validate[required, limitDate]" id="min_15" name="nb_place">
                                <option>  0</option>
                                <option value="1"> 1 </option>
                                <option value="2"> 2 </option>
                                <option value="3"> 3 </option>
                                <option value="4"> 4 </option>
                                <option value="5"> 5 </option>
                                <option value="6"> 6 </option>
                                <option value="7"> 7 </option>
                                <option value="8"> 8 </option>
                                <option value="9"> 9 </option>
                            </select>
                        </li>
                        <div class="clear"></div>
                    </ul>
                    <ul>
                        <li class="text-info">Additional Message :</li>
                        <li><textarea></textarea></li>
                        <div class="clear"></div>
                    </ul>
                    <input type="submit" value="Submit">
                    <div class="clear"></div>
            }
            </div>
    </div>
</div>
<div class="footer w3agile">
    <p>&copy 2021 Classy Booking Form . All rights reserved </p>
</div>

<!---main--->

Views/LogClient/ClientMenu.cshtml

@model SiteVol.Models.LogClient

@{
    ViewBag.Title = "ClientMenu";
    Layout = "~/Views/_LayoutPage2.cshtml";

}

<style>

    .jumbotron {
        background-color: #ff0000;
        color: #fff;
        padding: 250px 1px;
    }

    .jumbotron_bla {
        background-color: #fff;
        color: #ff0000;
        padding: 200px 1px;
    }
    /* Black buttons with extra padding and without rounded borders */
    .btn {
        padding: 10px 80px;
        background-color: #0094ff;
        color: #f1f1f1;
        border-radius: 0;
        transition: .2s;
    }

        /* On hover, the color of .btn will transition to white with black text */
        .btn:hover, .btn:focus {
            border: 1px solid #333;
            background-color: #fff;
            color: #000;
        }
</style>

<div class="row text-center">
    <div class="col-sm-6">
        <div class="jumbotron">
            <h1>Compagnie aérienne</h1>
            <p>On specialise dans la perfection</p>
        </div>

    </div>
    <div class="col-sm-6">


        <div class="jumbotron_bla">

            <h2>Bienvenu  @Model.clientName</h2>

            <br />
            <div class="input-group-btn">
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Vols")'"> Consulter les vols </button>
            </div>
            <br />
            <div class="input-group-btn">
                <button type="button" class="btn btn-danger"  onclick="location.href='@Url.Action("Recherche", "LogClient")'">  Rechercher les vols</button>
            </div>
            <br />
            <div class="input-group-btn">
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Vols")'">Réserver des vols </button>

            </div>
            <br />
            <div class="input-group-btn">
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("AnnulerReservation", "LogClient", new { name=@Model.clientName})'">Annuler réservation  </button>

            </div>
        </div>





    </div>

</div>

Views/LogClient/Login.cshtml

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/_LayoutPage1.cshtml";
}


<!--header-->
<div class="header-w3l">
    <h1> Login Client </h1>
</div>
<!--//header-->
<!--main-->
<div class="main-content-agile">
    <div class="sub-main-w3">
        <form action="Verify" method="post">
            <input placeholder="Username or E-mail" name="username" class="user" type="text" required=""><br>
            <input placeholder="Password" name="password" class="pass" type="password" required=""><br>
            <input type="submit" value="">
        </form>
    </div>
    <br />
    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Create", "Clients")'"> S'inscrire</button>
</div>



Views/LogClient/Recherche.cshtml

@{
    ViewBag.Title = "Recherche";
    Layout = "~/Views/_LayoutRecherche.cshtml";
}

<div id="booking" class="section">
    <div class="section-center">
        <div class="container">
            <div class="row">
                <div class="booking-form">
                    <form action="Rechercher" method="post">
                        <div class="form-group">
                            <div class="form-checkbox">
                                <label for="roundtrip">
                                    <input type="radio" id="roundtrip" name="flight-type">
                                    <span></span>Roundtrip
                                </label>
                                <label for="one-way">
                                    <input type="radio" id="one-way" name="flight-type">
                                    <span></span>One way
                                </label>
                                <label for="multi-city">
                                    <input type="radio" id="multi-city" name="flight-type">
                                    <span></span>Multi-City
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <span class="form-label">Ville de Depart</span>
                                    <input class="form-control" type="text" name="ville_depart" placeholder="City or airport">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <span class="form-label">Destination</span>
                                    <input class="form-control" type="text" name="destination" placeholder="City or airport">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <span class="form-label">Date de Depart</span>
                                    <input class="form-control" type="date" required>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <span class="form-label">Date de Retour</span>
                                    <input class="form-control" type="date" required>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <span class="form-label">Adultes (18+)</span>
                                    <select class="form-control">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                    </select>
                                    <span class="select-arrow"></span>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <span class="form-label">Enfants (0-17)</span>
                                    <select class="form-control">
                                        <option>0</option>
                                        <option>1</option>
                                        <option>2</option>
                                    </select>
                                    <span class="select-arrow"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <span class="form-label">classe de voyage</span>
                                    <select class="form-control">
                                        <option>Economy class</option>
                                        <option>Business class</option>
                                        <option>First class</option>
                                    </select>
                                    <span class="select-arrow"></span>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-btn">
                                    <button class="submit-btn">Afficher les Vols</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


Views/LogClient/Resultat.cshtml

@model IEnumerable<SiteVol.Models.VolComp>

@{
    ViewBag.Title = "Resultat";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string[] tabHeads = new string[]{"ID"
      ,"Nombre max de places"
      ,"Destination"
      ,"Lieu de depart"
      ,"Date de depart"
      ,"Prix"
      ,"Compagnie" };
}
<style>
    th {
        background-color: #0094ff;
        color: white;
    }
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>
<h2>Resultat</h2>

<br />

<div class="table">
    <table class="table table table-bordered table-hover">
        <thead>
            <tr>
                @{
                    foreach (var head in tabHeads)
                    {
                        <th>
                            @{
                                @head

                            }
                        </th>

                    }
                }

            </tr>

        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var data in Model)
                    {
                        <tr>
                            <td>@data.id </td>
                            <td> @data.nombre_max </td>
                            <td> @data.destination </td>
                            <td> @data.ville_depart </td>
                            <td> @data.date_depart </td>
                            <td> @data.prix </td>
                            <td> @data.compagnie </td>

                            <td>
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Booking", "LogClient",new{ id_vol=data.id, destination=data.destination, date_depart=data.date_depart, prix=data.prix, compagnie=data.compagnie })'">Réserver</button>

                                </div>
                            </td>
                        </tr>

                    }
                }
            }

        </tbody>

    </table>


</div>