Models/LogCompagnie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SiteVol.Models
{
    public class LogCompagnie
    {
        public String CompanyName { get; set; }
        public String name { get; set; }
        public String password { get; set; }

        
    }
}

Controllers/CompagniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteVol.Models;

namespace SiteVol.Controllers
{
    public class CompagniesController : Controller
    {
        private volDBEntities db = new volDBEntities();

        // GET: Compagnies
        public ActionResult Index()
        {
            return View(db.Compagnie.ToList());
        }

        // GET: Compagnies/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compagnie compagnie = db.Compagnie.Find(id);
            if (compagnie == null)
            {
                return HttpNotFound();
            }
            return View(compagnie);
        }

        // GET: Compagnies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Compagnies/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,nom,secteur,username,password")] Compagnie compagnie)
        {
            if (ModelState.IsValid)
            {
                db.Compagnie.Add(compagnie);
                db.SaveChanges();
                
            }

            return View(compagnie);
        }

        // GET: Compagnies/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compagnie compagnie = db.Compagnie.Find(id);
            if (compagnie == null)
            {
                return HttpNotFound();
            }
            return View(compagnie);
        }

        // POST: Compagnies/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,nom,secteur")] Compagnie compagnie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(compagnie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(compagnie);
        }

        // GET: Compagnies/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compagnie compagnie = db.Compagnie.Find(id);
            if (compagnie == null)
            {
                return HttpNotFound();
            }
            return View(compagnie);
        }

        // POST: Compagnies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Compagnie compagnie = db.Compagnie.Find(id);
            db.Compagnie.Remove(compagnie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/LogCompagnieController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiteVol.Models;

namespace SiteVol.Controllers
{
    
    public class LogCompagnieController : Controller
    {

        String CS = "Data Source =. ; database=volDB; Integrated Security = SSPI";
        SqlDataReader dr;
        
        List<VolComp> vol = new List<VolComp>();
        List<Place> place = new List<Place>();
        // GET: LogCompagnie
        [HttpGet]
        [Authorize]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Verify(LogCompagnie log)
        {
            
            using(SqlConnection con = new SqlConnection(CS)) 
            {
                SqlCommand cmd = new SqlCommand("select * from Compagnie where username = '" + log.name + "' and password = '" + log.password + "' ", con);
                con.Open();
                dr = cmd.ExecuteReader();
                if (dr.Read())
                {
                    log.CompanyName= log.name;
                    
                    
                    con.Close();
                    return View("CompangnieMenu", log);
                }
                else
                {
                    con.Close();
                    return View("Error");
                }
            }   

        }
        public void FeachData(String compa)
        {
            if (vol.Count>0)
            {
                vol.Clear();
            }
            try
            {
                SqlConnection con = new SqlConnection(CS);
                SqlCommand cmd = new SqlCommand("SELECT TOP 1000 [id],[nombre_max],[destination],[ville_depart],[date_depart],[prix],[compagnie] FROM [volDB].[dbo].[Vol] where compagnie='"+compa+"' ", con);
                con.Open();
                dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    vol.Add(new VolComp()
                    {
                        id = dr["id"].ToString(),
                        nombre_max = dr["nombre_max"].ToString(),
                        destination = dr["destination"].ToString(),
                        ville_depart = dr["ville_depart"].ToString(),
                        date_depart = dr["date_depart"].ToString(),
                        prix = dr["prix"].ToString(),
                        compagnie = dr["compagnie"].ToString()
                    });
                }
                con.Close();

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        
        public ActionResult AjouterSupprimerVols(String compa)
        {
            FeachData(compa);
            return View(vol);
        }
        public void FeachDataAutre(String name)
        {
            if (vol.Count > 0)
            {
                vol.Clear();
            }
            try
            {
                SqlConnection con = new SqlConnection(CS);
                SqlCommand cmd = new SqlCommand("SELECT TOP 1000 [id],[nombre_max],[destination],[ville_depart],[date_depart],[prix],[compagnie] FROM [volDB].[dbo].[Vol] where compagnie<>'" + name + "' ", con);
                con.Open();
                dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    vol.Add(new VolComp()
                    {
                        id = dr["id"].ToString(),
                        nombre_max = dr["nombre_max"].ToString(),
                        destination = dr["destination"].ToString(),
                        ville_depart = dr["ville_depart"].ToString(),
                        date_depart = dr["date_depart"].ToString(),
                        prix = dr["prix"].ToString(),
                        compagnie = dr["compagnie"].ToString()
                    });
                }
                con.Close();

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult AutreVols(String name)
        {
            FeachDataAutre(name);
            return View(vol);
        }

        public void FeachPlace()
        {
            if (place.Count > 0)
            {
                place.Clear();
            }
            try
            {
                SqlConnection con = new SqlConnection(CS);
                SqlCommand cmd = new SqlCommand("SELECT v.id,v.nombre_max,v.compagnie, SUM(r.nb_place) as reserve FROM Vol v,reservation r WHERE v.id=r.id_vol GROUP BY v.id,v.nombre_max,v.compagnie ORDER BY v.id  ", con);
                con.Open();
                dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    place.Add(new Place()
                    {
                        id = dr["id"].ToString(),
                        nombre_max = dr["nombre_max"].ToString(),
                        compagnie = dr["compagnie"].ToString(),
                        reserve = dr["reserve"].ToString()
                    }); ;
                }
                con.Close();

            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult AfficherPlace()
        {
            FeachPlace();
            return View(place);
        }
    }
}

Controllers/VolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteVol.Models;

namespace SiteVol.Controllers
{
    public class VolsController : Controller
    {
        private volDBEntities db = new volDBEntities();

        // GET: Vols
        public ActionResult Index()
        {
            return View(db.Vol.ToList());
        }
        public ActionResult Volii()
        {
            return View();
        }

        // GET: Vols/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vol vol = db.Vol.Find(id);
            if (vol == null)
            {
                return HttpNotFound();
            }
            return View(vol);
        }

        // GET: Vols/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vols/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nombre_max,destination,ville_depart,date_depart,prix,compagnie")] Vol vol)
        {
            if (ModelState.IsValid)
            {
                db.Vol.Add(vol);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vol);
        }

        // GET: Vols/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vol vol = db.Vol.Find(id);
            if (vol == null)
            {
                return HttpNotFound();
            }
            return View(vol);
        }

        // POST: Vols/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nombre_max,destination,ville_depart,date_depart,prix,compagnie")] Vol vol)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vol).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vol);
        }

        // GET: Vols/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vol vol = db.Vol.Find(id);
            if (vol == null)
            {
                return HttpNotFound();
            }
            return View(vol);
        }

        // POST: Vols/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Vol vol = db.Vol.Find(id);
            db.Vol.Remove(vol);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/LogCompagnie/AfficherPlace.cshtml
@model IEnumerable<SiteVol.Models.Place>

@{
    ViewBag.Title = "AfficherPlace";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string[] tabHeads = new string[]{"ID"
      ,"Nombre max de places"
      ,"Compagnie"
      ,"Nombre de Places Reservees"
      ,"Nombre de Places Disponibles"

    };
}

<style>
    th {
        background-color: #0094ff;
        color: white;
    }
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<h2>Les Place Disponibles </h2>

<br />

<div class="table">
    <table class="table table table-bordered table-hover">
        <thead>
            <tr>
                @{
                    foreach (var head in tabHeads)
                    {
                        <th>
                            @{
                                @head

                            }
                        </th>

                    }
                }

            </tr>

        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var data in Model)
                    {
                        <tr>
                            <td>@data.id </td>
                            <td> @data.nombre_max </td>
                            <td> @data.compagnie </td>
                            <td> @data.reserve </td>

                            @{ int dispo = Int32.Parse(@data.nombre_max) - Int32.Parse(@data.reserve);}

                            <td> @dispo </td>
 
                        </tr>

                    }
                }
            }

        </tbody>

    </table>


</div>


Views/LogCompagnie/AjouterSupprimerVols.cshtml
@model IEnumerable<SiteVol.Models.VolComp>

@{
    ViewBag.Title = "AjouterSupprimerVols";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string[] tabHeads = new string[]{"ID"
      ,"Nombre max de places"
      ,"Destination"
      ,"Lieu de depart"
      ,"Date de depart"
      ,"Prix"
      ,"Compagnie" };
}
<style>
    th {
        background-color: #0094ff;
        color: white;
    }
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<h2>Ajouter ou supprimer des vols </h2>
<br />
<div class="input-group-btn">
    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Create", "Vols")'"> Ajouter un nouveau Vol</button>

</div>
<br />

<div class="table">
    <table class="table table table-bordered table-hover">
        <thead>
            <tr>
                @{
                    foreach (var head in tabHeads)
                    {
                        <th>
                            @{
                                @head

                            }
                        </th>

                    }
                }

            </tr>

        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var data in Model)
                    {
                        <tr>
                            <td>@data.id </td>
                            <td> @data.nombre_max </td>
                            <td> @data.destination </td>
                            <td> @data.ville_depart </td>
                            <td> @data.date_depart </td>
                            <td> @data.prix </td>
                            <td> @data.compagnie </td>

                            <td>
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "Vols", new { id = data.id })'"> Supprimer</button>

                                </div>
                            </td>
                        </tr>

                    }
                }
            }

        </tbody>

    </table>


</div>

Views/LogCompagnie/AutreVols.cshtml
@model IEnumerable<SiteVol.Models.VolComp>

@{
    ViewBag.Title = "AutreVols";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string[] tabHeads = new string[]{"ID"
      ,"Nombre max de places"
      ,"Destination"
      ,"Lieu de depart"
      ,"Date de depart"
      ,"Prix"
      ,"Compagnie" };
}
<style>
    th {
        background-color: #0094ff;
        color: white;
    }
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<h2>AutreVols</h2>

<div class="table">
    <table class="table table table-bordered table-hover">
        <thead>
            <tr>
                @{
                    foreach (var head in tabHeads)
                    {
                        <th>
                            @{
                                @head

                            }
                        </th>

                    }
                }

            </tr>

        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var data in Model)
                    {
                        <tr>
                            <td>@data.id </td>
                            <td> @data.nombre_max </td>
                            <td> @data.destination </td>
                            <td> @data.ville_depart </td>
                            <td> @data.date_depart </td>
                            <td> @data.prix </td>
                            <td> @data.compagnie </td>
                        </tr>

                    }
                }
            }

        </tbody>

    </table>


</div>

Views/LogCompagnie/CompangnieMenu.cshtml

@model SiteVol.Models.LogCompagnie

@{
    ViewBag.Title = "CompangnieMenu";
    Layout = "~/Views/_LayoutPage2.cshtml";
    
}

<style>

    .jumbotron {
        background-color: #ff0000;
        color: #fff;
        padding: 250px 1px;
    }

    .jumbotron_bla {
        background-color: #fff;
        color: #ff0000;
        padding: 200px 1px;
    }
    /* Black buttons with extra padding and without rounded borders */
    .btn {
        padding: 10px 80px;
        background-color: #0094ff;
        color: #f1f1f1;
        border-radius: 0;
        transition: .2s;
    }

        /* On hover, the color of .btn will transition to white with black text */
        .btn:hover, .btn:focus {
            border: 1px solid #333;
            background-color: #fff;
            color: #000;
        }
</style>

<div class="row text-center">
    <div class="col-sm-6">
        <div class="jumbotron">
            <h1>Compagnie aérienne</h1>
            <p>On specialise dans la perfection</p>
        </div>

    </div>
    <div class="col-sm-6">


        <div class="jumbotron_bla">

            <h2>Bienvenu  @Model.CompanyName</h2>

            <br />
            <div class="input-group-btn">
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("AjouterSupprimerVols", "LogCompagnie",new {compa=@Model.CompanyName })'">Ajouter ou supprimer des vols</button>
            </div>
            <br />
            <div class="input-group-btn">
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("AfficherPlace", "LogCompagnie")'"> Afficher les places disponibles</button>
            </div>
            <br />
            <div class="input-group-btn">
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("AutreVols", "LogCompagnie",new {name =@Model.CompanyName })'">les vols des autres compagnies</button>
                
            </div>
        </div>





    </div>

</div>



Views/LogCompagnie/Create.cshtml

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

<h2>Log succesfully</h2>


Views/LogCompagnie/Edit.cshtml
@model SiteVol.Models.Vol

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vol</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre_max, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_max, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_max, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ville_depart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ville_depart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ville_depart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_depart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_depart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_depart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.compagnie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.compagnie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.compagnie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LogCompagnie/Login.cshtml

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

<!--header-->
<div class="header-w3l">
    <h1> Login Compagnie </h1>
</div>
<!--//header-->
<!--main-->
<div class="main-content-agile">
    <div class="sub-main-w3">
        <form action="Verify" method="post">
            <input placeholder="Username or E-mail" name="name" class="user" type="text" required=""><br>
            <input placeholder="Password" name="password" class="pass" type="password" required=""><br>
            <input type="submit" value="">
        </form>
    </div>
    <br />
    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Create", "Compagnies")'"> S'inscrire</button>
</div>

    




<!--//main-->
<!--footer-->

<!--//footer-->